<a href="https://colab.research.google.com/github/guilpassos/python/blob/main/Fuctura_Python3_Aula_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
minhaLista = (0, 1, 2, 3, 4, 5, 6, 7, 8)

In [4]:
meuArray = np.array(minhaLista)

In [5]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [7]:
minhaLista = list(range(9))

In [8]:
array1 = np.array(range(9))

In [9]:
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
array2 = np.arange(9)

In [12]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
array3 = np.arange(0, 10, 0.5)

In [14]:
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [15]:
novoArray = np.around(array3)

In [16]:
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [17]:
array3 = np.arange(0, 10, 0.5, dtype=int)

In [18]:
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
array4 = np.arange(12)

In [21]:
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
array4 = np.arange(12.)

In [23]:
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [24]:
type(array4)

numpy.ndarray

In [25]:
array4.dtype

dtype('float64')

In [26]:
print(array4.dtype)

float64


In [27]:
vetor1 = np.array([0, 1, 2, 3, 4])

In [28]:
print(vetor1)

[0 1 2 3 4]


In [29]:
vetor1[3]

3

In [30]:
vetor1[0: 2]

array([0, 1])

In [31]:
print(vetor1[0: 2])

[0 1]


In [32]:
s = np.array(["Python", "Profissional", "Java", "Água"])

In [33]:
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [34]:
s = np.array(['Python', 123456, 'Profissional', 'Java', 'Água'])

In [35]:
s

array(['Python', '123456', 'Profissional', 'Java', 'Água'], dtype='<U21')

In [36]:
vetor1[2] = 10

In [37]:
vetor1

array([ 0,  1, 10,  3,  4])

In [39]:
vetor1[0] = 4.5

In [40]:
vetor1

array([ 4,  1, 10,  3,  4])

In [43]:
minhaMatriz = np.array([[1, 2, 3], [4, 5, 6]])

In [44]:
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
minhaLista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [47]:
minhaMatriz = np.matrix(minhaLista)

In [48]:
minhaMatriz

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
x = np.zeros(3)

In [50]:
x

array([0., 0., 0.])

In [51]:
x = np.zeros((3, 2))

In [52]:
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
print(np.zeros(3))

[0. 0. 0.]


In [54]:
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [55]:
x = np.ones((5, 3))

In [56]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
y = np.ones(5)

In [58]:
y

array([1., 1., 1., 1., 1.])

In [61]:
matriz8 = np.array([[8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8], [8, 8, 8, 8]])

In [62]:
matriz8

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [66]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))

In [67]:
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [68]:
y = np.eye(5)

In [69]:
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
y = np.eye(5, dtype=int)

In [71]:
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [72]:
np.shape(minhaMatriz)

(3, 3)

In [73]:
minhaMatriz.shape

(3, 3)

In [74]:
type(minhaMatriz)

numpy.matrix

In [75]:
minhaMatriz.dtype

dtype('int64')

In [76]:
minhaMatriz[2, 1]

8

In [77]:
print(minhaMatriz[0,:])

[[1 2 3]]


In [78]:
print(minhaMatriz[:,2])

[[3]
 [6]
 [9]]


In [79]:
minhaMatriz[1, 0] = 100

In [80]:
minhaMatriz

matrix([[  1,   2,   3],
        [100,   5,   6],
        [  7,   8,   9]])

In [81]:
np.sum(meuArray)

36

In [82]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
np.prod(meuArray)

0

In [84]:
np.cumsum(meuArray)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [86]:
meuArray.min()

0

In [87]:
meuArray.max()

8

In [88]:
np.mean(meuArray)

4.0

In [89]:
np.median(meuArray)

4.0

In [90]:
np.var(meuArray)

6.666666666666667

In [91]:
np.std(meuArray)

2.581988897471611